# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d986ce53bbcacc2cd9289216d9583b0d98eb6d1641f7f754d9a7d1b6ab33429efbf75f40f8b6ac62fda50c6673b033bef85e4925f0f85842df3dcd7c122e3ad

test:
  secret_key_base: 9819a9c37955cae69faef77d48fdeb2e6b193fad293b319e94f61e59cca48f5dc8feeb79ad2a6f46accd25aed98e4b96423ed0d46ce848f2373ccfcd94b0546e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
